[features]
seeds = false
skip-lint = false

[programs.localnet]
stablecoin_core = "SSSCore1111111111111111111111111111111111"
transfer_hook = "SSSHook1111111111111111111111111111111111"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
