[features]
seeds = false
skip-lint = false

[programs.localnet]
stablecoin_core = "Ak9Rhow3tv2Df5u1ZVFWXqdUqeXynjGAhHGZ8qN4dJ6G"
transfer_hook = "4A8pvyAMvPqypVh1gdgswu4YAsZfFDocQnWbvtnGP4bs"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
